version: "3.8"
services:
  backend:
    build: .
    environment:
      - LOG_FILE=/data/sample.log
      - CACHE_DB_PATH=/data/intelsentry_cache.db
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
